name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_API_KEY: ${{ secrets.DATABRICKS_API_KEY }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SQL_HTTP: ${{ secrets.SQL_HTTP }}
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: make install
      - name: format
        run: make format
      - name: lint
        run: make lint
      - name: test
        run: make test
